version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    container_name: db

  backend:
    image: jans0n27/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
    container_name: kittygram_backend

  frontend:
    env_file: .env
    image: jans0n27/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    depends_on:
      - backend
    volumes:
      - static:/frontend_static

  gateway:
    image: jans0n27/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/app/static/
      - media:/app/media/
